version: 1.0.0
slug: nginx_proxy
name: NGINX Home Assistant SSL
description: NGINX
url: https://github.com/Reydan46/ha-addon/tree/main/nginx
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
image: homeassistant/{arch}-addon-nginx_proxy
map:
  - ssl
  - share
options:
  domain: null
  server: null
  certfile: homeassistant.crt
  keyfile: homeassistant.key
  cloudflare: false
  customize:
    active: false
    default: nginx/nginx_default*.conf
    servers: nginx/conf/*.conf
  hsts: max-age=31536000; includeSubDomains
ports:
  443/tcp: 8122
  80/tcp: null
schema:
  domain: str
  server: str
  certfile: str
  keyfile: str
  cloudflare: bool
  customize:
    active: bool
    default: str
    servers: str
  hsts: str
